import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInAnonymously,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getDatabase,ref,get,set,update,onValue,runTransaction,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js';
import {firebaseConfig} from './firebase-config.js';
import {QUESTIONS} from './questions.js';
const appEl=document.getElementById('app'),statusEl=document.getElementById('status');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,cls='')=>`<button data-action="${action}" class="${cls}">${label}</button>`;
let db,auth,uid,code='',role='',room=null,unsub=null,offset=0,finalizing=false,lastRender='',timer;
const configured=!Object.values(firebaseConfig).some(v=>String(v).includes('HIER_'));
const msg=(s,bad=false)=>{statusEl.textContent=s;statusEl.className=bad?'error':'success'};
const path=p=>ref(db,`rooms/${code}${p?'/'+p:''}`);
const slots=()=>Object.entries(room?.slots||{}).sort(([a],[b])=>+a-+b);
const me=()=>slots().find(([,p])=>p.uid===uid);
const players=()=>slots().length;
const now=()=>Date.now()+offset;
const remaining=()=>Math.max(0,Math.ceil(((room?.meta?.deadline||0)-now())/1000));
const gameQuestion=()=>QUESTIONS[room?.meta?.qid]||QUESTIONS[0];
const getAnswerCount=()=>Object.keys(room?.answers?.[room?.meta?.round]||{}).length;
function showHome(){appEl.innerHTML=`<div class="panel"><h2>Willkommen im Duell!</h2><p class="muted">Jedes Handy öffnet dieselbe Internetadresse. Der Schiedsrichter erstellt das Spiel.</p>${btn('👨‍⚖️ Spiel als Schiedsrichter erstellen','create')}<hr style="border-color:#4a4574;margin:24px 0"><label for="roomcode">Spielcode eingeben</label><input id="roomcode" maxlength="6" autocomplete="off" placeholder="z. B. K7M2PA" style="text-transform:uppercase"><label for="playername">Dein Spielername</label><input id="playername" maxlength="24" placeholder="z. B. Emma">${btn('🎮 Als Spieler beitreten','join','secondary')}</div>`}
function render(){if(!room){showHome();return}let m=room.meta,host=role==='host',stage=m.stage,q=gameQuestion(),myAnswer=room.answers?.[m.round]?.[uid];let content='';
if(stage==='lobby'){
 content=`<div class="panel"><p class="muted">Spielcode für die 4 Spieler</p><div class="code">${esc(code)}</div><p class="muted small">Code auf den anderen Handys eingeben. ${players()}/4 Plätze belegt.</p>${slots().map(([n,p])=>`<div class="player">${n}. ${esc(p.name)} ${p.uid===uid?'(du)':''}</div>`).join('')}${host?`<p class="muted">Du leitest das Spiel. Starte, sobald alle vier da sind.</p>${btn('🚀 Battle starten','start',players()===4?'':'secondary')}`:'<p>⏳ Warten auf den Schiedsrichter …</p>'}</div>`;
}else if(stage==='question'){
 const opts=q.options.map((o,i)=>`<button class="answer ${myAnswer?.choice===i?'selected':''}" data-action="answer" data-choice="${i}" ${myAnswer?'disabled':''}>${'ABCD'[i]} · ${esc(o)}</button>`).join('');
 content=`<div class="panel"><div class="row"><span class="tag">FRAGE ${esc(m.round)} / 30 · STATION ${q.station}</span><span class="timer" id="countdown">${remaining()}s</span></div><div class="bar" style="margin:15px 0"><div class="fill" id="progress" style="width:${remaining()*5}%"></div></div><h2>${esc(q.question)}</h2>${host?`<p>🧑‍⚖️ ${getAnswerCount()} von ${players()} Antworten eingegangen</p>${btn('⏭ Runde sofort auswerten','finish','secondary')}`:`<div class="answers">${opts}</div><p class="muted">${myAnswer?'✅ Antwort gespeichert. Warte auf die Auswertung!':'Tippe deine Antwort an. Nur eine Auswahl möglich!'}</p>`}</div>`;
}else if(stage==='result'){
 const ans=room.answers?.[m.round]||{};
 content=`<div class="panel"><span class="tag">RUNDE ${esc(m.round)} GESCHAFFT</span><h2>${esc(q.question)}</h2><p class="success">✓ Richtig: ${esc(q.options[q.correct])}</p>${slots().map(([,p])=>`<div class="row player"><span>${esc(p.name)} ${ans[p.uid]?(ans[p.uid].choice===q.correct?'✅':'❌'):'⌛'}</span><strong>${p.score||0} Punkte</strong></div>`).join('')}${host?btn(+m.round>=30?'🏆 Sieger anzeigen':'➡️ Nächste Frage','next'):'<p class="muted">⏳ Der Schiedsrichter startet die nächste Frage.</p>'}</div>`;
}else if(stage==='done'){
 const ranking=slots().map(([n,p])=>p).sort((a,b)=>(b.score||0)-(a.score||0));
 content=`<div class="panel"><h2>🏆 BATTLE BEENDET!</h2><p class="muted">Alle 30 Fragen sind geschafft.</p>${ranking.map((p,i)=>`<div class="player row"><span>${['🥇','🥈','🥉','🎖️'][i]} ${esc(p.name)}</span><span class="score">${p.score||0}</span></div>`).join('')}<p class="success">${ranking.length>1&&ranking[0].score===ranking[1].score?'Punktgleichstand an der Spitze!':'Glückwunsch an '+esc(ranking[0]?.name||'alle Spieler')+'!'}</p>${host?btn('🔄 Neues Spiel mit denselben Spielern','restart','secondary'):''}</div>`;
}
 appEl.innerHTML=`<div class="row"><span class="muted small">Raum ${esc(code)} · ${host?'🧑‍⚖️ Schiedsrichter':'🎮 '+esc(me()?.[1]?.name||'Spieler')}</span>${btn('Verlassen','leave','secondary')}</div>${content}`;
}
async function connect(c,r){if(unsub)unsub();code=c;role=r;localStorage.setItem('vb_session',JSON.stringify({code,role}));unsub=onValue(path(''),snap=>{room=snap.val();if(!room){msg('Spielraum wurde gelöscht.',true);leave();return}render()},err=>{msg('Verbindung zum Spielraum fehlgeschlagen: '+err.message,true)});}
async function create(){const c=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');code=c;await set(path('meta'),{hostUid:uid,stage:'lobby',round:'0',qid:0,deadline:0});await connect(c,'host');msg('Spielraum erstellt!');}
async function join(){let c=document.getElementById('roomcode')?.value.trim().toUpperCase(),name=document.getElementById('playername')?.value.trim();if(!/^[A-Z2-9]{6}$/.test(c)||!name){msg('Bitte sechsstelligen Code und Namen eingeben.',true);return}code=c;let snap=await get(path('meta'));if(!snap.exists()){msg('Spielcode nicht gefunden.',true);return}if(snap.val().stage!=='lobby'){msg('Das Spiel läuft bereits.',true);return}for(let i=1;i<=4;i++){let r=await runTransaction(path('slots/'+i),cur=>cur===null?{uid,name,score:0}:undefined,{applyLocally:false});if(r.committed){await connect(c,'player');msg('Du bist dabei!');return}if(r.snapshot.val()?.uid===uid){await connect(c,'player');return}}msg('Alle vier Plätze sind belegt.',true)}
async function start(){if(role!=='host)'{msg('Es müssen genau vier Spieler dabei sein.',true);return}await advance(1)}
async function advance(n){if(role!=='host')return;if(n>30){await update(path('meta'),{stage:'done'});return}await update(path('meta'),{stage:'question',round:String(n),qid:n-1,deadline:now()+20000});}
async function answer(choice){if(role!=='player'||room?.meta?.stage!=='question'||remaining()===0)return;const r=room.meta.round;if(room.answers?.[r]?.[uid])return;await set(path(`answers/${r}/${uid}`),{choice,at:serverTimestamp()}).catch(e=>msg('Antwort nicht gespeichert: '+e.message,true));}
async function finish(){if(role!=='host'||room?.meta?.stage!=='question'||finalizing)return;finalizing=true;try{let m=room.meta,q=gameQuestion(),a=room.answers?.[m.round]||{},changes={};for(let [n,p] of slots()){let v=a[p.uid];let pts=0;if(v&&v.choice===q.correct){let t=Math.max(0,Math.min(20,(m.deadline-v.at)/1000));pts=100+Math.floor(t/20*50)}changes[`slots/${n}/score`]=(p.score||0)+pts}changes['meta/stage']='result';await update(path(''),changes)}catch(e){msg('Auswertung fehlgeschlagen: '+e.message,true)}finally{finalizing=false}}
async function restart(){if(role!=='host')return;const changes={'meta/stage':'lobby','meta/round':'0','meta/deadline':0};for(let [n] of slots())changes[`slots/${n}/score`]=0;await update(path(''),changes);msg('Neue Runde bereit. Alte Antworten werden nicht wiederverwendet.');}
function leave(){unsub?.();unsub=null;room=null;code='';role='';localStorage.removeItem('vb_session');showHome()}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action;b.disabled=true;try{if(a==='create')await create();if(a==='join')await join();if(a==='start')await start();if(a==='answer')await answer(+b.dataset.choice);if(a==='finish')await finish();if(a==='next')await advance(+room.meta.round+1);if(a==='restart')await restart();if(a==='leave')leave()}catch(err){msg(err.message||String(err),true)}finally{if(b.isConnected)b.disabled=false}});
if(!configured){appEl.innerHTML='<div class="panel"><h2>⚙️ Firebase einrichten</h2><p>Trage zuerst die Konfiguration deines Firebase-Projekts in <strong>firebase-config.js</strong> ein. Danach veröffentliche die Web-App gemäß ANLEITUNG.md.</p></div>'}else{try{const fb=initializeApp(firebaseConfig);auth=getAuth(fb);db=getDatabase(fb);onValue(ref(db,'.info/serverTimeOffset'),s=>offset=s.val()||0);await signInAnonymously(auth);uid=auth.currentUser.uid;const session=JSON.parse(localStorage.getItem('vb_session')||'null');if(session?.code&&session?.role){code=session.code;const s=await get(path(''));if(s.exists()&&(session.role==='host'?s.val().meta?.hostUid===uid:Object.values(s.val().slots||{}).some(p=>p.uid===uid)))await connect(code,session.role);else{localStorage.removeItem('vb_session');showHome()}}else showHome();msg('Online verbunden.')}catch(e){appEl.innerHTML='<div class="panel"><h2>Verbindung fehlgeschlagen</h2><p>Prüfe Firebase-Konfiguration, anonyme Anmeldung und Datenbankregeln.</p></div>';msg(e.message,true)}}
setInterval(()=>{if(!room)return;const t=document.getElementById('countdown');if(t)t.textContent=remaining()+'s';const p=document.getElementById('progress');if(p)p.style.width=remaining()*5+'%';if(role==='host'&&room.meta?.stage==='question'&&remaining()===0)finish()},250);
