// Originalfragen auf Basis der Vokabellisten Unit 2, Station 1 und 2.
export const QUESTIONS = [
[1,'Was bedeutet „canoeing“?',['Kanufahren','Schwimmen','Skifahren','Klettern'],0],
[1,'Wie heißt „Wildwasser-Rafting“?',['skiing','rafting','netball','rugby'],1],
[1,'Was bedeutet „swimming“?',['Rudern','Rennen','Schwimmen','Springen'],2],
[1,'Was bedeutet „netball“?',['Volleyball','Basketball','Rugby','Netball'],3],
[1,'Wie heißt „Skifahren“?',['skiing','swimming','rafting','canoeing'],0],
[1,'Was bedeutet „small“?',['laut','klein','langsam','groß'],1],
[1,'Was bedeutet „loud“?',['leise','langweilig','laut','schwer'],2],
[1,'Wie heißt „langsam“?',['quick','safe','bad','slow'],3],
[1,'Was bedeutet „boring“?',['langweilig','gefährlich','anstrengend','begabt'],0],
[1,'Wie heißt „gefährlich“?',['successful','dangerous','safe','patient'],1],
[1,'Was bedeutet „unfit“?',['begabt','geduldig','unsportlich','erfolgreich'],2],
[1,'Was bedeutet „tough“?',['sicher','frech','einfach','hart / anstrengend'],3],
[1,'Wie heißt „Ausrüstung“?',['equipment','rules','trip','woods'],0],
[1,'Was bedeutet „patient“?',['frech','geduldig','erschöpft','gefährlich'],1],
[1,'Was bedeutet „exhausted“?',['erfolgreich','sportlich','erschöpft','begabt'],2],
[2,'Was bedeutet „plaster“?',['Verband','Gips','Tablette','Pflaster'],3],
[2,'Wie heißt „Verband“?',['bandage','cast','tooth','tablet'],0],
[2,'Was bedeutet „ambulance“?',['Polizei','Krankenwagen','Küstenwache','Feuerwehr'],1],
[2,'Was bedeutet „tooth“?',['Knie','Hand','Zahn','Fuß'],2],
[2,'Wie heißt „Gips“?',['tablet','plaster','bandage','cast'],3],
[2,'Was bedeutet „accident“?',['Unfall','Notruf','Wunde','Verband'],0],
[2,'Wie heißt „bluten“?',['burn','bleed','sprain','hurt'],1],
[2,'Was bedeutet „knee“?',['Knöchel','Finger','Knie','Zahn'],2],
[2,'Wie heißt „verstauchen“?',['bleed','burn','call','sprain'],3],
[2,'Was bedeutet „burn“?',['verbrennen','verbinden','verstauchen','anrufen'],0],
[2,'Was bedeutet „emergency services“?',['Feuerwehrhaus','Notfalldienste','Krankenhaus','Polizeiwache'],1],
[2,'Wie heißt „anrufen“?',['say','give','call','have'],2],
[2,'Was bedeutet „stay with“?',['weglaufen','anrufen','warten auf','bei jemandem bleiben'],3],
[2,'Wie heißt „Feuerwehr“?',['fire brigade','coastguard','police','ambulance'],0],
[2,'Was bedeutet „coastguard“?',['Polizei','Küstenwache','Feuerwehr','Krankenwagen'],1]
].map(([station,question,options,correct],id)=>({id,station,question,options,correct}));
